######################################################################
# Automatically generated by qmake (3.0) ?? ??? 24 13:04:55 2016
######################################################################
QT += widgets
QT += core
QT += gui
TEMPLATE = app
TARGET = proj
INCLUDEPATH += .

# Input
HEADERS += mywindow.h
SOURCES += main.cpp mywindow.cpp
